//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFORMWIN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"function cancelSign2(){
	var callback = function(){
		var messageJson = {
			resultCode : ""R03""
		};

		window.chrome.webview.postMessage(JSON.stringify(messageJson));
	}

	if(gTokenId != ''){
		var param = {};
		param.toknId = gTokenId;
		param.hstUseId = gFormMetaData.common.useHstId;

		$.ajax({
	          url    : '/DelSignTokn.ajax'
	        , type   : 'POST'
	        , data   : param
	        , dataType : 'json'
	        , success:function(data, textStatus, jqXHR){
	        	if(data.result == 'S'){
					hidePopupLoadingIndicator();
					gTokenId = '';

					alert('서명이 취소 되었습니다.');
					callback();
	        	}
	        	closeAllPopup();
	        }
			, error : function( jqXHR, textStatus, errorThrown ){
				closeAllPopup();
			}
		});
	}else{
		closeAllPopup();
		callback();
	}
}

function clickSignCompletePopup2(){
	gSignCompletePopup.close();
	window.chrome.webview.postMessage(JSON.stringify(gSignCompleteDataPopup));
}")]
        public string AddFunc {
            get {
                return ((string)(this["AddFunc"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"exec_typ_cd\": \"S\",\r\n    \"op_data\": {\r\n        \"EQP_MDL_NM\": \"휴대폰 모델명\",\r\n " +
            "       \"EQP_SER_NUM\": \"일련번호\",\r\n        \"CUST_TYP_ETC\": \"기타\",\r\n        \"OUT_PRC\":" +
            " \"출고가\",\r\n        \"MTH_AVG_DATA_USE_QTY\": \"데이터\",\r\n        \"MTH_AVG_VOICE_USE_QTY\"" +
            ": \"음성\",\r\n        \"MTH_AVG_LTR_USE_QTY\": \"문자\",\r\n        \"PRCPLN_NM\": \"선택 요금제명\",\r\n" +
            "        \"TOT_FEE_DC\": \"총 요금할인(24개월 기준)\",\r\n        \"EQP_SUPRT_AMT\": \"단말기 지원금\",\r\n " +
            "       \"CUST_NM\": \"고객명\",\r\n        \"DIV_RPAY_MTH_CNT\": \"개월\",\r\n        \"MBL_PHON_C" +
            "NTRCT_GUID_YN\": \"\",\r\n        \"TOT_SUPRT_AMT\": \"총 지원금\",\r\n        \"SUPRT_AMT\": \"지원" +
            "금\",\r\n        \"FRGNR_YN\": \"\",\r\n        \"ETC_DC\": \"기타할인\",\r\n        \"EQP_PRC\": \"단말대" +
            "금\",\r\n        \"CASH_BUY_PRC\": \"현금구입가\",\r\n        \"MTH_FIXAMT\": \"월정액\",\r\n        \"TO" +
            "T_DC_AMT\": \"총 할인액\",\r\n        \"FEE_AGRMT_DC_AMT\": \"요금약정할인\",\r\n        \"SEL_AGRMT_D" +
            "C_AMT\": \"선택약정할인\",\r\n        \"MTH_EQP_BUY_COST\": \"휴대폰 구입비\",\r\n        \"MTH_COMM_FEE" +
            "\": \"통신요금\",\r\n        \"MTH_PAY_AMT\": \"합계\",\r\n        \"EQP_DC_AMT\": \"단말할인\",\r\n       " +
            " \"EQP_PAYBK_AMT\": \"현금 페이백\",\r\n        \"RTN_AMT_DIV_RPAY_AMT\": \"반환금/분할상환금\",\r\n     " +
            "   \"TOT_DIV_RPAY_CMMS\": \"총 분할상환수수료\",\r\n        \"NEW_SAFE_NUM\": \"신규 안심번호(T안심콜)\",\r\n" +
            "        \"USIM_SER_NUM\": \"USIM\",\r\n        \"GRTM_CL_CD\": \"CASH\", /* 보증금 */ /* CASH" +
            "|EXMPT|INSU */ /* 현금|면제|보증보험 */ \r\n        \"DATA_ROMING_CD\": \"ROMING_ONEPASS\", /*" +
            " 데이터 로밍 */ /* ROMING_ONEPASS|ISOL */ /* T로밍 원패스|차단 */ \r\n        \"TMOA_COPN_NUM\":" +
            " \"T모아쿠폰 No.\",\r\n        \"CNTC_NUM\": \"연락가능한 전화번호\",\r\n        \"BILL_ISUE_TYP_CD\": \"S" +
            "MBIL\", /* 청구서 수신 방법 */ /* SMBIL|SMSMMS_BILL|EMAIL_BILL|T_WLD|BILL_NREQ|ETC|PDF_B" +
            "ILL */ /* 스마트청구서|문자청구서|이메일청구서|T world확인|청구서 미신청|기타|바로보는 요금안내서 */ \r\n        \"INV_" +
            "EMAIL_ADDR\": \"이메일청구서\",\r\n        \"INTEG_SVC_NUM\": \"통합번호\",\r\n        \"BANK_CARD_CO_" +
            "NM\": \"은행(카드사)명\",\r\n        \"BANK_CARD_NUM\": \"계좌(카드)번호\",\r\n        \"DPST_CARD_OWNR_" +
            "NM\": \"예금주(카드주)\",\r\n        \"DPST_CARD_OWNR_BIRTH_DT\": \"예금주(카드주)법정생년월일\",\r\n        " +
            "\"CARD_EFF_PRD_YR\": \"카드유효기간 년\",\r\n        \"CARD_EFF_PRD_MTH\": \"카드유효기간 월\",\r\n       " +
            " \"DPST_CARD_OWNR_REL_NM\": \"관계\",\r\n        \"NP_SVC_NUM\": \"이동할 전화번호\",\r\n        \"BF_" +
            "COMM_CO_CL_CD\": \"KT\", /* 변경 전 통신회사 */ /* KT|LGU|MVNO */ /* KT|LG U+|MVNO */ \r\n  " +
            "      \"BF_COMM_CO_CL_NM\": \"MVNO\",\r\n        \"NP_AUTH_CD\": \"USIM_SER_NUM_LAST_4\", " +
            "/* 번호이동 인증방법 (택1) */ /* USIM_SER_NUM_LAST_4|CRDT_CARD_NUM_LAST_4|BANK_NUM_LAST_4" +
            "|GIRO */ /* 단말기(USIM) 일련번호 뒷 네자리|신용카드 번호 뒷 네자리|요금납부 은행 계좌 또는 합산 청구번호 뒷 네자리|지로납부 " +
            "*/ \r\n        \"CORP_REQR_NM\": \"이름\",\r\n        \"USE_FEE_PAY_MTHD_CD\": \"IMPAY\", /* 이" +
            "달 사용요금 */ /* IMPAY|LPAY */ /* 즉시납부|청구서 받은 후 납부 */ \r\n        \"NY_RFND_AMT_FEE_SET" +
            "OFF_CD\": \"AGREE\", /* 미 환급액 요금상계 */ /* AGREE|NY_AGREE */ /* 동의|미동의 */ \r\n        \"" +
            "EQP_AL_FRAY_KEEP_CD\": \"ALLOT_FPAY\", /* 단말기 할부 */ /* ALLOT_FPAY|ALLOT_KEEP */ /* " +
            "할부완납|할부지속 (변경 전 통신회사에서 청구) */ \r\n        \"OTCO_NUM_CHG_PLUS\": [\r\n            \"REQ" +
            "\",\r\n            \"/* 타사번호변경플러스: 신청 */\"\r\n        ],\r\n        \"OPR_NM\": \"판매자\",\r\n   " +
            "     \"SHOP_PHON_NUM\": \"연락처\",\r\n        \"BIRTH_DT\": \"950101\",\r\n        \"AGNT_NM\": " +
            "\"이름(위임받는 분)\",\r\n        \"LEGAL_REPVE_NM\": \"법정대리인\",\r\n        \"GATE_ODER_FORM_NUM\":" +
            " \"비대면 주문번호(신청서번호)\",\r\n        \"GATE_SELF_SIGN_CD\": \"비대면 본인 서명 구분 코드\",\r\n        \"G" +
            "ATE_LEGAL_SIGN_CD\": \"비대면 법정대리인 서명 구분 코드\",\r\n        \"SCUR_GR_CD\": [\r\n            " +
            "\"ONLINE_SVC_PERM_REJT\",\r\n            \"AGNT_SVC_PERM_REJT\",\r\n            \"2LN_OVR" +
            "_SVC_PERM_REJT\",\r\n            \"3LN_OVR_SVC_PERM_REJT\",\r\n            \"/* 보안등급 설정:" +
            " 온라인 개통 허용안함|대리인 개통 허용안함|2회선 초과 개통 허용안함|3회선 초과 개통 허용안함 */\"\r\n        ],\r\n        " +
            "\"T_WLD_TC_DTL_OFR_YN\": \"Y\", /* T world 요금확인 통화내역 신청 */ /* REQ|CNCL */ /* 신청|신청 취" +
            "소 */ \r\n        \"FMLY_1_CUST_NM\": \"이름\",\r\n        \"FMLY_1_SVC_NUM\": \"이동전화번호\",\r\n   " +
            "     \"FMLY_1_BIRTH_DT\": \"법정생년월일\",\r\n        \"FMLY_1_REP_REL_NM\": \"가족대표와의 관계\",\r\n  " +
            "      \"FMLY_2_CUST_NM\": \"이름\",\r\n        \"FMLY_2_SVC_NUM\": \"이동전화번호\",\r\n        \"FML" +
            "Y_2_BIRTH_DT\": \"법정생년월일\",\r\n        \"FMLY_2_REP_REL_NM\": \"가족대표와의 관계\",\r\n        \"FM" +
            "LY_3_CUST_NM\": \"이름\",\r\n        \"FMLY_3_SVC_NUM\": \"이동전화번호\",\r\n        \"FMLY_3_BIRTH" +
            "_DT\": \"법정생년월일\",\r\n        \"FMLY_3_REP_REL_NM\": \"가족대표와의 관계\",\r\n        \"FMLY_4_CUST" +
            "_NM\": \"이름\",\r\n        \"FMLY_4_SVC_NUM\": \"이동전화번호\",\r\n        \"FMLY_4_BIRTH_DT\": \"법정" +
            "생년월일\",\r\n        \"FMLY_4_REP_REL_NM\": \"가족대표와의 관계\",\r\n        \"USIM_PAY_TYP_CD\": \"I" +
            "MPAY\", /* USIM */ /* IMPAY|NXT_MON_TOT|REUSE|ESIM */ /* 즉납|다음달 요금 합산|재사용|eSIM */" +
            " \r\n        \"DATA_HLMT\": \"5000_WON\", /* 데이터 상한 */ /* 5000_WON|10000_WON|15000_WON" +
            " */ /* 5,000|10,000|15,000 */ \r\n        \"TING_PRCPLN_CHRG_PERM_AMT_SET_CD\": \"500" +
            "0_WON\", /* 팅요금제 충전 허용금액 설정 */ /* 5000_WON|10000_WON|15000_WON|20000_WON|ETC_WON " +
            "*/ /* 5,000원|10,000원|15,000원|20,000원|기타 */ \r\n        \"LEGAL_REPVE_CNTC_NUM\": \"이동" +
            " 전화번호\",\r\n        \"WLESS_CNTNTS_SAMT_STL_RST_YN\": \"Y\", /* 무선콘텐츠 소액결제 이용제한 */ \r\n  " +
            "      \"LEGAL_REPVE_SIGN_YN\": \"법정대리인 서명 여부\",\r\n        \"SILV_EXCLSV_PRCPLN_CD\": \"N" +
            "EW_SILV_PRCPLN\", /* 실버전용 요금제 */ /* NEW_SILV_PRCPLN|TGRP_SILV|TPLAN_SNIR_SPCL|BAN" +
            "D_SILV_SAV|SILV_SMART_15|TPLAN_SNIR_ESSNC|BAND_SILV_12G|GOLD_AGE_15|TPLAN_SNIR_S" +
            "AV_45|BAND_SILV_22G|GOLD_AGE_34|TPLAN_SNIR_SAV_28|TPLAN_SNIR_SAV */ /* T끼리 어르신|T" +
            "플랜 시니어 스페셜|뉴실버요금제|T플랜 시니어 에센스|band 어르신 세이브|실버스마트15|T플랜 시니어 안심4.5G|band 어르신 1.2G|" +
            "골든에이지15|T플랜 시니어 안심2.8G|band 어르신 2.2G|골든에이지34|T플랜 시니어 세이브 */ \r\n        \"SILV_PRCP" +
            "LN_GUID_YN\": \"Y\", /* 실버전용 요금제와 기타 가입 요금제의 안내를 받음 */ \r\n        \"TRNSFR_REQR_CL_CD" +
            "\": \"SELF\", /* 명의를 주는자 */ /* SELF|AGNT|LEGAL_REPVE */ /* 본인|대리인|법정대리인 */ \r\n      " +
            "  \"T_GLXY_CLUB_ZERO_SCRB_YN\": \"Y\", /* T 갤럭시 클럽제로 신청여부 */ \r\n        \"CHKR_POST_SH" +
            "OP_NM\": \"확인(통화)자 소속 영업장명\",\r\n        \"CHECK_EMP_NM\": \"확인자(직원) 성명\",\r\n        \"TRNS" +
            "FR_CNTC_NUM\": \"양도인 연락처\",\r\n        \"CHECK_DTM\": \"통화일시\",\r\n        \"PASSPORT_NUM\": " +
            "\"여권번호\",\r\n        \"REQR_CL_CD\": \"SELF\", /* 방문 고객 */ /* SELF|AGNT|LEGAL_REPVE */ /" +
            "* 본인|대리인|법정대리인 */ \r\n        \"EQP_AGRMT_SUCES_YN\": \"Y\", /* 약정승계단말기 변경 잔여 할부기간 이월 " +
            "*/ \r\n        \"EQP_REM_ALLOT_SUPRT_AMT\": \"잔여할부할인금 이월\",\r\n        \"AGN_NM\": \"대리점\",\r" +
            "\n        \"EQP_ALLOT_AMT\": \"할부금액\",\r\n        \"REQ_SVC_NUM\": \"신규가입 번호(WiBro ID)\",\r\n" +
            "        \"RUSER_REL_CD\": \"EMP\", /* 명의고객과의 관계 */ /* EMP|OFFCR */ /* 직원|임원 */ \r\n   " +
            "     \"MBR_USE_DTL_AD_RCV_AGREE_YN\": \"AGREE\", /* 멤버십 이용내역 광고 수신 동의 */ /* AGREE|NY" +
            "_AGREE */ /* 동의합니다.|동의하지 않습니다. */ \r\n        \"STRD_GUID_SUPL_SVC_ID\": \"부가상품ID\",\r\n" +
            "        \"EQP_MFACT_NM\": \"단말 제조사\",\r\n        \"IMEI_NUM\": \"IMEI 정보 (15자리 숫자)\",\r\n   " +
            "     \"WIFI_MAC_ADDR\": \"Wi-Fi MAC 주소 (12자리 영/숫자 혼용)\",\r\n        \"NW_MTHD_CD\": \"WCD" +
            "MA\", /* 네트워크 유형 */ /* WCDMA|LTE|ETC|5G */ /* 3G(WCDMA)|4G(LTE)|기타|5G */ \r\n      " +
            "  \"EQP_TYP_CL_CD\": \"SMPHON\", /* 단말 유형 */ /* SMPHON|TBLT|ETC */ /* 스마트폰|태블릿|기타 */" +
            " \r\n        \"FREQ_SUPRT_YN\": \"YES\", /* 당사 주파수 지원 여부 */ /* YES|NO */ /* 예|아니오 */ \r" +
            "\n        \"SMS_MMS_STRD_SUPRT_YN\": \"YES\", /* 당사 SMS/MMS 규격 지원 여부 */ /* YES|NO */ " +
            "/* 예|아니오 */ \r\n        \"SHOP_ORG_ID\": \"처리영업장코드\",\r\n        \"FEE_PAY_MTHD_CD\": \"ATR" +
            "NF\", /* 요금납부 방법 */ /* ATRNF|DPST_EXCLSV_BANK|GIRO */ /* 자동이체 신청|입금전용계좌|지로 */ \r\n " +
            "       \"BILL_ISUE_TYP_YN\": \"Y\", /* 요금확인 방법 */ \r\n        \"MTH_EQP_BUY_COST_CL_CD\"" +
            ": \"EQP_BUY_DIV\", /* 휴대폰 구입비 */ /* EQP_BUY_DIV|EQP_BUY_CASH|EQP_BUY_MATE */ /* 분할" +
            "상환( 개월)|현금|T렌탈 */ \r\n        \"SML_AMT_SETTL_PWD_YN\": \"Y\", /* 안전한 결제를 위해 비밀번호를 꼭 설" +
            "정하시기 바랍니다. */ \r\n        \"SHOP_ADDR\": \"주소\",\r\n        \"WLF_DC_CD\": \"HNDCAP\", /* 개인" +
            " */ /* HNDCAP|HNDCAP_CHILD_WLF_FCLT_ADMINR|BAS_LIFE_SPDMR_DWL_EDU|BAS_LIFE_SPDMR" +
            "_MEDIC_LIVI|SSUP_LIFE_SPDMR|PUB_MERI|MANY_CHLD_HOUS|SILV_HOUS|BAS_PENSN_SPDMR */" +
            " /* 장애인|장애인(아동)복지시설운영자|기초생활수급자(주거/교육)|기초생활수급자(의료/생계)|차상위계층|국가유공자|다자녀가구|실버가구|기초연금" +
            "수급자 */ \r\n        \"RDTN_CL_CD\": \"SPCL_SCH\", /* 법인 */ /* SPCL_SCH|PUB_MERI_ASO|HND" +
            "CAP_CHILD_WLF_CORP|HNDCAP_CHILD_WLF_ASO */ /* 특수학교|국가유공자단체|장애인(아동)복지법인|장애인(아동)복지" +
            "단체 */ \r\n        \"SUPRT_AMT_MTHD_CD\": \"FEE_DC\", /* 지원금 방식 선택 */ /* FEE_DC|NOTC_SU" +
            "PM */ /* 가. 지원금 상응 요금할인|나. 단말기 지원금 */ \r\n        \"DIV_RPAY_YN\": \"Y\", /* 분할상환 */ /" +
            "* DIV_RPAY|DIV_RPAY_FRN|LUMPS|MATE_RENT|TWD_RENT */ /* 분할상환|외국인분할상환|일시납|테이크임대|T렌" +
            "탈(TWD) */ \r\n        \"JOIN_CARD_AMT\": \"제휴카드 금액\",\r\n        \"WBR_ID\": \"(WiBro ID)\"," +
            "\r\n        \"TAX_BILL_ISUE_YN\": \"Y\", /* 세금계산서 발행 */ \r\n        \"INTEG_INV_YN\": \"Y\"," +
            " /* 동일명의 통합청구 */ \r\n        \"SH_TM_RCV_YN\": \"Y\", /* 신한T주거래통장TM수신동의 */ \r\n        \"" +
            "NP_AUTH_LAST_4\": \"번호이동 인증방법 뒷 네자리\",\r\n        \"FMLY_REP_YN\": \"Y\", /* 대표여부 */ \r\n  " +
            "      \"RGCUST_SCRB_YN\": \"Y\", /* 단골고객 가입 여부 */ \r\n        \"LEGAL_REPVE_BIRTH_DT\": " +
            "\"법정생년월일\",\r\n        \"CUST_TYP_CD\": \"INDV\", /* 고객구분 */ /* INDV|BIZR|CORP|PUB_INST|" +
            "ETC */ /* 개인|개인사업자|법인|공공기관|기타 */ \r\n        \"IPHON_YN\": \"Y\", /* 아이폰 여부 */ \r\n     " +
            "   \"AGNT_BIRTH_DT\": \"법정생년월일\",\r\n        \"TING_PRCPLN_CHRG_PERM_AMT_SET_ETC\": \"기타\"" +
            ",\r\n        \"MBL_PHON_NUM\": \"휴대폰\",\r\n        \"DSNET_ADD_SUPRT_AMT\": \"유통망 추가지원금\",\r\n" +
            "        \"EQP_REM_ALLOT_MTH\": \"개월\",\r\n        \"VISIT_CUST\": \"SELF\", /* 방문고객 */ /* " +
            "SELF|AGNT|LEGAL_REPVE */ /* 본인|대리인|법정대리인 */ \r\n        \"NW_MTHD_ETC\": \"기타\",\r\n    " +
            "    \"EQP_TYP_CL_ETC\": \"기타\",\r\n        \"JOIN_CARD_YN\": \"Y\", /* 제휴카드 여부 */ \r\n      " +
            "  \"AGRMT_PRD_MTH_CNT\": \"약정기간\",\r\n        \"CORP_REQR_BIRTH_DT\": \"법정생년월일\",\r\n       " +
            " \"AGNT_REL_CD\": \"010\", /* 대리인관계코드 */ /* 010|021|031|041|050|061|070|080|090|101|" +
            "110|990 */ /* 본인|부모|배우자|형제/자매|자녀|친척|친구/연인|외국인|해당법인직원|후견인|법인등기이사|기타 */ \r\n        " +
            "\"MBR_BAS_ADDR\": \"멤버십 기본주소\",\r\n        \"MBR_DTL_ADDR\": \"멤버십 상세주소\",\r\n        \"MBR_Z" +
            "IP\": \"멤버십 우편번호\",\r\n        \"LEGAL_CTZ_NUM\": \"주민등록번호\",\r\n        \"COURT_AGNT_REL_CD" +
            "\": \"010\", /* 법정대리인관계코드 */ /* 010|021|031|041|050|061|070|080|090|101|110|990 */ " +
            "/* 본인|부모|배우자|형제/자매|자녀|친척|친구/연인|외국인|해당법인직원|후견인|법인등기이사|기타 */ \r\n        \"ADD_PROD_L" +
            "IST_ID\": \"부가요금제/부가서비스\",\r\n        \"PRCPLN_ID\": \"선택 요금제명\",\r\n        \"ZIP\": \"주소\",\r\n" +
            "        \"CORP_REG_NUM\": \"법인등록번호\",\r\n        \"BIZ_REG_NUM\": \"사업자등록번호\",\r\n        \"F" +
            "RGNR_RGST_NUM\": \"외국인등록번호\",\r\n        \"AGNT_CNTC_NUM\": \"연락받을 전화번호\",\r\n        \"BAS_" +
            "ADDR\": \"주소\",\r\n        \"DTL_ADDR\": \"주소\",\r\n        \"OMD_YN\": \"OMD 여부\",\r\n        \"T" +
            "PET_YN\": \"TPET 여부\",\r\n        \"DPST_CARD_OWNR_CNTC_NUM\": \"예금주(카드주)이동전화번호\",\r\n     " +
            "   \"FMLY_DIV_DATA_REQ_YN\": \"\",\r\n        \"PT\": \"포인트\",\r\n        \"SVC_AGRMT_DC_CD\":" +
            " [\r\n            \"AA\",\r\n            \"AB\",\r\n            \"AG\",\r\n            \"/* 서비스" +
            "약정할인코드: 이동전화 요금약정할인|태블릿 요금약정할인|선택약정할인 */\"\r\n        ],\r\n        \"SVC_AGRMT_PRD_CD" +
            "\": [\r\n            \"D0365\",\r\n            \"D0730\",\r\n            \"M0012\",\r\n        " +
            "    \"M0024\",\r\n            \"/* 서비스약정기간코드: 365 일|730 일|12 개월|24 개월 */\"\r\n        ]," +
            "\r\n        \"DPST_CARD_OWNR_REL_CD\": \"010\", /* 예금주카드주 관계 */ /* 010|021|031|041|050" +
            "|061|070|080|090|101|110|990 */ /* 본인|부모|배우자|형제/자매|자녀|친척|친구/연인|외국인|해당법인직원|후견인|법인" +
            "등기이사|기타 */ \r\n        \"ALLOT_INT_AMT\": \"총 분할상환 수수료(연 5.9%)\",\r\n        \"EQP_MTH_AL" +
            "TM\": \"휴대폰 월 분할상환금(A)\",\r\n        \"MTH_FIXAMT_PRCPLN\": \"월 정액요금\",\r\n        \"MTH_FEE" +
            "_DC_AMT\": \"월 요금할인\",\r\n        \"MTH_BAS_PAY_AMT\": \"월 기본 납부액(A)+(B)\",\r\n        \"DC_" +
            "PEN_M12\": \"위약금(12개월째)\",\r\n        \"DC_PEN_M18\": \"위약금(18개월째)\",\r\n        \"CUST_CL_C" +
            "D\": \"GNRL\", /* 고객구분 */ /* GNRL|TEEN|SILV */ /* 일반|청소년|실버 */ \r\n        \"NEW_OP_CL" +
            "_CD\": [\r\n            \"MBL_PHON_NEW\",\r\n            \"NP\",\r\n            \"NP_RECALL\"" +
            ",\r\n            \"PRE_POST_PAY_CNVT\",\r\n            \"USIM_SVC\",\r\n            \"WBR\"," +
            "\r\n            \"EQP_CHG\",\r\n            \"/* 업무 구분: 이동전화 신규|번호이동|번호이동 철회|선후불 전환|USI" +
            "M 개통|WiBro|단말기변경 */\"\r\n        ],\r\n        \"OLD_EQP_MDL_NM\": \"중고단말 모델명\",\r\n       " +
            " \"OLD_EQP_IMEI\": \"중고단말 IMEI\",\r\n        \"OLD_EQP_SER_NUM\": \"중고단말 일련번호\",\r\n        " +
            "\"OLD_EQP_CNTC_NUM\": \"이동전화번호\",\r\n        \"OLD_EQP_BANK_NM\": \"은행명(계좌송금시)\",\r\n       " +
            " \"OLD_EQP_DPST_OWNR_NM\": \"예금주(계좌송금시)\",\r\n        \"OLD_EQP_BANK_NUM\": \"계좌번호(계좌송금시)" +
            "\",\r\n        \"PPAY_AMT\": \"선 납부금\",\r\n        \"MBR_NEWISU_YN\": \"AGREE\", /* 멤버십신규발급여부" +
            " */ /* AGREE|NY_AGREE */ /* 예|아니오 */ \r\n        \"MBR_OP_CL_CD\": \"SCRB\", /* 업무 유형 " +
            "*/ /* SCRB|REISU|TYP_CHG|TMP_SUSP_REQ|TMP_SUSP_REL|MBR_SCSS */ /* 신규가입|재발급|종류변경|" +
            "일시정지 신청|일시정지 해제|멤버십 탈퇴 */ \r\n        \"SMS_AGREE_YN\": \"\",\r\n        \"OCB_ACCUM_AGRE" +
            "E_YN\": \"\",\r\n        \"MBR_WPHON_NUM\": \"멤버십 유선전화\",\r\n        \"EVENT_ID\": \"비대면 예약번호\"" +
            ",\r\n        \"TS_VAL_NO\": \"비대면 차수\",\r\n        \"SVC_SCHD_DT\": \"비대면 예약일\",\r\n        \"T" +
            "OT_USE_FEE\": \"총 이용료(24개월기준)\",\r\n        \"MTH_USE_FEE\": \"월 이용료\",\r\n        \"CNTRCT_" +
            "STA_DT\": \"계약시작일\",\r\n        \"CNTRCT_END_DT\": \"계약종료일\",\r\n        \"SVC_CHG_CD\": \"업무구" +
            "분\",\r\n        \"BILL_ISUE_TYP_CD_NM\": \"청구서발행유형명\",\r\n        \"MATE_MID_TERM_AMT\": \"T" +
            "렌탈  중도해지금(1~24개월)\",\r\n        \"MATE_MTH_USE_FEE_1\": \"T렌탈 월이용료(1~24개월)\",\r\n        " +
            "\"MATE_MTH_USE_FEE_2\": \"T렌탈 월이용료(25~36개월)\",\r\n        \"MATE_AGRMT_PRD_MTH_CNT\": \"T" +
            "렌탈 약정기간\",\r\n        \"MATE_MTH_USE_FEE\": \"T렌탈 월 이용료(신규신청서용)\",\r\n        \"FEE_PAY_MT" +
            "HD_NM\": \"납부방법\",\r\n        \"CELL_CHG_PSBL_DT\": \"반납가능일\",\r\n        \"MATE_MID_TERM_AM" +
            "T_M12\": \"T렌탈 중도해지금(12개월)\",\r\n        \"MATE_MID_TERM_AMT_M18\": \"T렌탈 중도해지금(18개월)\",\r" +
            "\n        \"DISTR_SMS_REV_IMPSBL_OBJ_MDL_YN\": \"재난문자 미수신 단말 여부\",\r\n        \"CURR_EQP" +
            "_MDL_NM\": \"기기모델\",\r\n        \"CURR_EQP_MFACT_NM\": \"제조사\",\r\n        \"CURR_EQP_SER_NU" +
            "M\": \"단말 일련번호\",\r\n        \"SEL_AGREE_SIGN_UNUSE_YN\": \"선택동의서명 미사용여부\",\r\n        \"EID" +
            "\": \"애플EID\",\r\n        \"LEGAL_REPVE_EMAIL\": \"법정대리인 이메일\",\r\n        \"LEGAL_CNTC_NUM_" +
            "SKT_YN\": \"Y\", /* 법정대리인 연락처 SKT회선여부 */ \r\n        \"PSAFE4_OCB_REQ_YN\": \"캐쉬백 제휴서비스 " +
            "동의\",\r\n        \"ASVC_OUT_PRC\": \"개통후출고가\",\r\n        \"ASVC_TOT_SUPRT_AMT\": \"개통후총지원금\"" +
            ",\r\n        \"LEGAL_REPVE_CNTC_NUM_2\": \"법정대리인 일반연락처\",\r\n        \"LEGAL_CNTC_NUM2_SK" +
            "T_YN\": \"Y\", /* 법정대리인 일반연락처 SKT회선여부 */ \r\n        \"OKSUSU_POINT_REQ\": \"PT_01\", /* " +
            "OKSUSU 패키지 포인트 */ /* PT_01|PT_02 */ /* 포인트3000|포인트10000 */ \r\n        \"DISTR_POCK" +
            "ETFI_YN\": \"포켓파이교체대상여부\",\r\n        \"TO_2G_SERVICE_YN\": \"2G 단말기 교체 프로그램 동의 여부\",\r\n  " +
            "      \"TOT_USE_FEE_RENT\": \"총 이용금액(T렌탈)\",\r\n        \"SUB_PROD_ID\": \"부가혜택상품ID\",\r\n  " +
            "      \"OCALL_NUM_DISP_TXT\": \"번호연결서비스기타\",\r\n        \"TO_2G_SERVICE_BTN_YN\": \"2G 대상" +
            "전환 식지여부\",\r\n        \"FADE_OUT_2G_BTN_YN\": \"LTE전환대상\",\r\n        \"ASVC_DIV_RPAY_MTH_" +
            "CNT\": \"개통후 할부개월\",\r\n        \"ASVC_SEL_AGRMT_DC_AMT\": \"개통후 선택약정할인\",\r\n        \"ASVC" +
            "_MTH_COMM_FEE\": \"개통후 통신요금\",\r\n        \"ASVC_PRCPLN_NM\": \"개통후 선택 요금제\",\r\n        \"C" +
            "NVT_REQ_NUM\": \"010전환신청전화번호\",\r\n        \"NUM_INTEG_NP_REQ_SVC_CD\": \"GEN_NP\", /* 01" +
            "0번호통합관련 번호이동신청서비스 */ /* GEN_NP|NUM_DISP */ /* 세대간 번호이동|01X번호표시 서비스 */ \r\n        " +
            "\"NUM_DISP_REQ_KEEP_YN\": \"AGREE\", /* 01X번호표시 서비스 지속여부 */ /* AGREE|NY_AGREE */ /* " +
            "예|아니오 */ \r\n        \"NUM_INTEG_NP_SVC_YN\": \"010번호통합서비스여부\",\r\n        \"NUM_DISP_REQ" +
            "_KEEP_NP_YN\": \"AGREE\", /* 01X번호표시 서비스 지속여부(번호이동용) */ /* AGREE|NY_AGREE */ /* 예|아" +
            "니오 */ \r\n        \"OCALL_NUM_DISP_NP\": \"GEN_NP_TYP\", /* 01X번호표시 서비스(번호이동용) */ /* G" +
            "EN_NP_TYP|OPEN_TYP|LTR_TYP|ETC */ /* 세대간번호이동|공개|문자|기타 */ \r\n        \"FADE_OUT_SUP" +
            "RT_CD\": \"FEE_DC\", /* LTE전환지원금방식 */ /* FEE_DC|NOTC_SUPM|PPAY_SUPRT */ /* 월요금할인|단말" +
            "기 지원금|선불전환지원 */ \r\n        \"ASVC_PPAY_AMT\": \"개통후선납금\",\r\n        \"CUST_BASE_VR_ZIP\"" +
            ": \"VR 배송 우편번호\",\r\n        \"CUST_BASE_VR_BAS_ADDR\": \"VR 배송 기본주소\",\r\n        \"CUST_B" +
            "ASE_VR_DTL_ADDR\": \"VR 배송 상세주소\",\r\n        \"SVC_5G_REQ_YN\": \"AGREE\", /* 5G서비스신청여부 " +
            "*/ /* AGREE|NY_AGREE */ /* 동의|미동의 */ \r\n        \"ASC369_PSNL_INFO_THDP_AGREE_YN\":" +
            " \"AGREE\", /* 추가 서비스(안심보상+369) 제공동의 및 개인정보 제3자 활용동의 */ /* AGREE|NY_AGREE */ /* 동의" +
            "|비동의 */ \r\n        \"EQP_SIM_TYPE\": \"단말기 SIM유형\",\r\n        \"ADD_EQP_MDL_NM\": \"부가단말 " +
            "모델명\",\r\n        \"ADD_EQP_SER_NUM\": \"부가단말 일련번호\",\r\n        \"TOT_OUT_PRC\": \"총합계 출고가\"" +
            ",\r\n        \"ADD_OUT_PRC\": \"부가단말출고가\",\r\n        \"TID_PSNINF_PRA_YN\": \"Y\", /* T 아이디" +
            " 가입을 위한 개인정보 수집 및 이용 동의 */ /* Y|N */ /* 예|아니오 */ \r\n        \"BAS_ADDR_5G\": \"5G 주생" +
            "활지역 주소(기본주소)\",\r\n        \"CHLD_GRAD\": \"자녀 학년\",\r\n        \"CHLD_CNTC_NUM\": \"자녀 연락처\"" +
            ",\r\n        \"IMEI_NUM2\": \"IMEI2 (15자리 숫자)\",\r\n        \"OMD_EID\": \"OMD EID (32자리 숫자" +
            ")\",\r\n        \"SUBS_DLVR_REQ_DT\": \"구독배송희망일\",\r\n        \"SUBS_INDPND1_OPT_NM_1\": \"구" +
            "독단독상품1_옵션명1\",\r\n        \"SUBS_INDPND1_OPT_NM_2\": \"구독단독상품1_옵션명2\",\r\n        \"SUBS_I" +
            "NDPND2_OPT_NM_1\": \"구독단독상품2_옵션명1\",\r\n        \"SUBS_INDPND2_OPT_NM_2\": \"구독단독상품2_옵션명" +
            "2\",\r\n        \"SUBS_INDPND3_OPT_NM_1\": \"구독단독상품3_옵션명1\",\r\n        \"SUBS_INDPND3_OPT" +
            "_NM_2\": \"구독단독상품3_옵션명2\",\r\n        \"SUBS_INDPND4_OPT_NM_1\": \"구독단독상품4_옵션명1\",\r\n     " +
            "   \"SUBS_INDPND4_OPT_NM_2\": \"구독단독상품4_옵션명2\",\r\n        \"SUBS_INDPND5_OPT_NM_1\": \"구" +
            "독단독상품5_옵션명1\",\r\n        \"SUBS_INDPND5_OPT_NM_2\": \"구독단독상품5_옵션명2\",\r\n        \"ADD_PR" +
            "OD_PRICE_LIST_NM\": \"부가상품명목록\",\r\n        \"HPSTL_SAFE_NOTI_SVC\": \"AGREE\", /* 휴대폰결제 " +
            "안심통보서비스 */ /* AGREE|NREQ */ /* 이용동의|미신청 */ \r\n        \"OLD_PAY_TYP_CD\": \"PRE_DC\"," +
            " /* 지급방법 */ /* PRE_DC|TRNSF|PPAY */ /* 단말할부 선할인|계좌이체|요금선납 */ \r\n        \"GLXY_FE_" +
            "CLUB_TYP\": \"S23\", /* 갤럭시 FE클럽 가입 코드 */ /* S23 */ /* 갤럭시S23FE클럽 */ \r\n        \"PRE" +
            "_AGRMT_PRD_CD\": \"M12_PLUS_AGRMT\", /* 약정기간 사전신청 */ /* M12_PLUS_AGRMT */ /* 12개월사전" +
            "신청 */ \r\n        \"DATA_COMB_DC_RTN_CHECK_YN\": \"비대면서명용_할인반환금 확인\",\r\n        \"DATA_T" +
            "BLT_DC_RTN_CHECK_YN\": \"비대면서명용_할인반환금 확인\",\r\n        \"EQP_TRAD_CNTRCT_YN\": \"비대면서명용_" +
            "단말매매 계약 관련 고객 안내사항\",\r\n        \"EQP_TRAD_STPL_YN\": \"비대면서명용_단말매매약관\",\r\n        \"FEE" +
            "_DC_SYS_SCRB_AGREE_YN\": \"비대면서명용_할인반환금 확인\",\r\n        \"GLXY_CLUBN_PSNINF_OFR_YN\": " +
            "\"비대면서명용_개인정보 제 3자 제공\",\r\n        \"GLXY_CLUBN_PSNINF_PRA_YN\": \"비대면서명용_개인정보 수집 및 이용" +
            " 동의\",\r\n        \"OKSUSU_PAGR_01_YN\": \"비대면서명용_개인정보의 수집ㆍ이용\",\r\n        \"OKSUSU_PAGR_" +
            "02_YN\": \"비대면서명용_개인정보 제3자 제공 [SK텔레콤㈜ 귀중]\",\r\n        \"OKSUSU_PAGR_03_YN\": \"비대면서명용_" +
            "정보제공 수신동의\",\r\n        \"OKSUSU_PAGR_04_YN\": \"비대면서명용_고객혜택 제공을 위한 개인정보 수집. 이용, 취급위탁 " +
            "및 정보/광고 수신동의\",\r\n        \"OKSUSU_PAGR_05_YN\": \"비대면서명용_개인맞춤형 혜택/정보제공 위한 3자 제공동의\",\r" +
            "\n        \"PREM_CLUB_PSNINF_OFR_YN\": \"비대면서명용_개인정보 제 3자 제공\",\r\n        \"PREM_CLUB_P" +
            "SNINF_PRA_YN\": \"비대면서명용_개인정보 수집 및 이용 동의\",\r\n        \"PREM_CLUB2_CMP_YN\": \"비대면서명용_분" +
            "실/파손 시 보상예시 (분실 시 동일기기 보상 원칙)\",\r\n        \"PREM_CLUB2_IDNT_OFR_YN\": \"비대면서명용_고유식별정" +
            "보 수집ㆍ이용ㆍ제공 동의\",\r\n        \"PREM_CLUB2_PSNINF_OFR_YN\": \"비대면서명용_개인정보 제3자 제공\",\r\n    " +
            "    \"PREM_CLUB2_PSNINF_PRA_YN\": \"비대면서명용_개인정보 수집 및 이용 동의\",\r\n        \"PSAFE_AS_PSN" +
            "INF_OFR_YN\": \"비대면서명용_개인정보 제 3자 제공\",\r\n        \"PSAFE_AS_PSNINF_PRA_YN\": \"비대면서명용_개" +
            "인정보 수집 및 이용 동의\",\r\n        \"PSAFE4_CMP_AGREE_YN\": \"비대면서명용_보상관련 동의\",\r\n        \"PSA" +
            "FE4_MAIN_CTT_AGREE_YN\": \"비대면서명용_폰세이프IV 주요 내용\",\r\n        \"PSAFE4_PSNINF_OFR_YN\": " +
            "\"비대면서명용_개인정보 제 3자 제공 동의\",\r\n        \"PSAFE4_PSNINF_PRA_YN\": \"비대면서명용_개인정보 수집/이용 동의" +
            "\",\r\n        \"PSNINF_PAGR_01_YN\": \"비대면서명용_개인정보ㆍ개인위치정보 수집ㆍ이용 동의\",\r\n        \"PSNINF" +
            "_PAGR_02_YN\": \"비대면서명용_서비스 제공을 위한 개인정보 제3자 제공 동의\",\r\n        \"PSNINF_PAGR_03_YN\": " +
            "\"비대면서명용_개인신용정보 조회 동의\",\r\n        \"PSNINF_PAGR_04_YN\": \"비대면서명용_고유식별정보(주민등록번호/외국인등록" +
            "번호/여권번호) 처리 동의\",\r\n        \"PSNINF_PAGR_05_YN\": \"비대면서명용_할상환 등 서비스제공을 위한 개인정보 제3자 " +
            "제공 동의\",\r\n        \"PSNINF_PAGR_06_YN\": \"비대면서명용_고객 혜택 제공을 위한 정보 이용 관련 동의\",\r\n      " +
            "  \"PSNINF_PAGR_07_YN\": \"비대면서명용_고객 혜택 정보 및 광고 수신 동의\",\r\n        \"PSNINF_PAGR_08_YN" +
            "\": \"비대면서명용_반환금/할부금 조회 동의\",\r\n        \"PSNINF_PAGR_09_YN\": \"비대면서명용_T에코/New보상기변/클럽T" +
            "조기기변/프리클럽반납 가입자 정보 제3자 제공 동의\",\r\n        \"PSNINF_PAGR_10_YN\": \"비대면서명용_은행 제휴 상품 안내" +
            "를 위한 정보 제공 동의\",\r\n        \"RGCUST_ADD_RCV_AGREE_YN\": \"비대면서명용_정보/광고 전송을 위한 개인정보 이용" +
            " 및 정보/광고 수신 동의\",\r\n        \"RGCUST_CLCT_AGREE_YN\": \"비대면서명용_단골고객관리 서비스를 위한 개인정보 수집" +
            "/이용 동의\",\r\n        \"RGCUST_SKT_AGREE_YN\": \"비대면서명용_단골고객관리 서비스를 위한 SK텔레콤㈜의 개인정보 제공 " +
            "동의\",\r\n        \"RGCUST_USE_ACQR_AGREE_YN\": \"비대면서명용_정보/광고 전송을 위한 개인정보(위치정보 포함) 이용," +
            " 취급위탁, 제공 및 정보/광고 수신\",\r\n        \"SEL_AGRMT_DC_SCRB_AGREE_YN\": \"비대면서명용_할인반환금 확인\"," +
            "\r\n        \"SPDMR_NM\": \"비대면서명용_복지할인 수급자\",\r\n        \"T_GLXY_CLUB_PSNINF_OFR_YN\": \"" +
            "비대면서명용_개인정보 제3자 제공\",\r\n        \"T_GLXY_CLUB_PSNINF_PRA_YN\": \"비대면서명용_개인정보 수집 및 이용 " +
            "동의\",\r\n        \"T_IPHON_CLUB_CMP_ATTDM_YN\": \"비대면서명용_분실/파손 시 보상 유의사항\",\r\n        \"T" +
            "_IPHON_CLUB_CMP_YN\": \"비대면서명용_분실/파손 시 보상예시 (분실 시 동일기기 보상 원칙)\",\r\n        \"T_IPHON_" +
            "CLUB_PSNINF_OFR_YN\": \"비대면서명용_개인정보 제3자 제공\",\r\n        \"T_IPHON_CLUB_PSNINF_PRA_YN\"" +
            ": \"비대면서명용_개인정보 수집 및 이용 동의\",\r\n        \"T_SIG_FIN_TRBL_INSU_YN\": \"비대면서명용_금융사고보상 보험" +
            "\",\r\n        \"T_SIG_PSNINF_OFR_YN\": \"비대면서명용_개인정보 제3자 제공\",\r\n        \"TPET_PSNINF_P" +
            "RA_AGREE_YN\": \"비대면서명용_개인정보 수집ㆍ이용에 대한 동의 (위치정보 포함)\",\r\n        \"TPET_SVC_STPL_AGRE" +
            "E_YN\": \"비대면서명용_T pet 서비스 이용약관 (위치기반서비스 포함)\",\r\n        \"MBL_PHON_SVC_ADD_INFO_YN\"" +
            ": \"비대면서명용_이동전화서비스 추가 안내여부\",\r\n        \"PSNINF_PAGR_11_YN\": \"비대면서명용_요금연체사실 통지를 위한 " +
            "개인정보 제3자 제공 동의\",\r\n        \"PSNINF_PAGR_12_YN\": \"비대면서명용_SK브로드밴드 연계 개인맞춤형 혜택/정보 제공" +
            " 위한 제3자 제공 및 정보/광고\",\r\n        \"PSNINF_PAGR_13_YN\": \"비대면서명용_SK브로드밴드 연계 고객 혜택 제공을 " +
            "위한 개인정보 처리위탁 동의\",\r\n        \"CELDISC_STPL_AGREE_YN\": \"비대면 척척할인 이용약관에 동의\",\r\n      " +
            "  \"CELDISC_PSNINF_PRA_YN\": \"비대면  척척할인 개인정보 수집 및 이용 동의\",\r\n        \"CELDISC_PSNINF" +
            "_OFR_YN\": \"비대면  척척할인  제3자 정보제공 동의\",\r\n        \"CELDISC_INSU_PSNINF_OFR_YN\": \"비대면 " +
            "척척할인  제휴 보험사 상품 소개 목적의 제3자 정보제공 동의\",\r\n        \"ENCCARD_STPL_AGREE_YN\": \"비대면 EnCl" +
            "ean Bonus Card 서비스 가입신청\",\r\n        \"legal_cntc_num2_skt_yn\": null,\r\n        \"leg" +
            "al_repve_cntc_num_2\": null,\r\n        \"eappl_op_typ_cd\": \"OP02A10001\",\r\n        \"" +
            "eappl_op_typ_ver_num\": \"0001\",\r\n        \"eappl_op_typ_eff_sta_dt\": \"20240520\"\r\n " +
            "   },\r\n    \"uscan_info\": {\r\n        \"ORG_ID\": \"testshop\",\r\n        \"USER_ID\": \"사" +
            "용자ID\",\r\n        \"LOGIN_ID\": \"로그인ID\",\r\n        \"USER_NM\": \"사용자명\"\r\n    }\r\n}")]
        public string testJson {
            get {
                return ((string)(this["testJson"]));
            }
            set {
                this["testJson"] = value;
            }
        }
    }
}
